### ISSUE TITLE
Elevator in the moonshine co-op building doesn't work

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#419]
When i try to select the floor, it shows my inventory

**Comment by Oskutin** [comment]
Fixed

**Comment by xiv72** [comment]
Fixed in next release?

**Comment by Oskutin** [comment]
Yep

**Comment by xiv72** [comment]
It's not really fixed. It worked when i tried to go up. Once I tried to go down, again I couldn't select the floor. Then if i went down and called the elevator, i couldn't get in anymore.....

**Comment by whudson** [comment]
This elevator is still broken, you can take it up to the shroom grow room but then you're stuck there because it won't let you select the floor a 2nd time, it just brings up the inventory.
